global:
  postgresql:
    auth:
      postgresPassword: postgres
      username: postgres
      password: postgres
      database: postgres

#      existingSecret: crud-secrets
#      secretKeys:
#        userPasswordKey: db-password
#        adminPasswordKey: db-password
#        username: db-username
#        database: db-name