apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.service.name}}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: {{.Values.application.backend.metricsPort}}
  selector:
    app: crud-backend