{
 "title": "CRUD Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{uri!~\".*swagger.*|.*actuator.*\", status=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile (0.5, sum by (le) (rate(http_server_requests_seconds_bucket{uri!~\".*swagger.*|.*actuator.*\"}[1m])))"
    },
    {
     "expr": "histogram_quantile (0.95, sum by (le) (rate(http_server_requests_seconds_bucket{uri!~\".*swagger.*|.*actuator.*\"}[1m])))"
    },
    {
     "expr": "histogram_quantile (0.99, sum by (le) (rate(http_server_requests_seconds_bucket{uri!~\".*swagger.*|.*actuator.*\"}[1m])))"
    },
    {
     "expr": "histogram_quantile (1, sum by (le) (rate(http_server_requests_seconds_bucket{uri!~\".*swagger.*|.*actuator.*\"}[1m])))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count{uri!~\".*swagger.*|.*actuator.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}